################################################################################
# FUNDING.yml for Ryzhand-Overlay Repository
# Author: Dimasick-git
# Description:
#   This FUNDING.yml file is used to configure the sponsor button for the Ryzhand Overlay
#   repository on GitHub. It specifies the supported funding model platforms and their
#   respective account information.
#
#   GitHub Repository: https://github.com/Dimanchikgshehsbshene/Ryzhand-Overlay
#
################################################################################

github: Dimasick-git
ko_fi: Dimasick-git
