################################################################################
# FUNDING.yml for Overlayandandhand-Overlay Repository
# Author: Dimasick-git 
# Description:
#   This FUNDING.yml file is used to configure the sponsor button for the Ryazhahand Overlay
#   repository on GitHub. It specifies the supported funding model platforms and their
#   respective account information.
#
#   GitHub Repository: https://github.com/Dimasick-git/Ryazhahand-Overlay
#
################################################################################

github: Dimasick-git 
ko_fi: Dimasick-git 

