; Author: Dimasick-git
[update]
delete sdmc:/config/ryazhahand/downloads/sdout.zip
download https://github.com/Dimasick-git/Ryazhahand-Overlay/releases/latest/download/sdout.zip sdmc:/config/ryazhahand/downloads/
unzip sdmc:/config/ryazhahand/downloads/sdout.zip sdmc:/
delete sdmc:/config/ryazhahand/downloads/sdout.zip
