;version=0.3.4
;creator=Dimasick-git
;about='This package contains commands to update/install a variety of overlays and packages.'

[*Install Overlay]
json_file_source '/switch/.packages/Easy Installer/overlays.json' name

try:
delete /config/ryazhahand/downloads/zip-url.json
download {json_file_source(*,zip-url)} /config/ryazhahand/downloads/zip-url.json
json_file /config/ryazhahand/downloads/zip-url.json
download {json_file(0,assets,{json_file_source(*,download-entry)},browser_download_url)} /config/ryazhahand/downloads/{json_file(0,assets,{json_file_source(*,download-entry)},name)}
unzip /config/ryazhahand/downloads/{json_file(0,assets,{json_file_source(*,download-entry)},name)} /config/ryazhahand/downloads/zip-url/
move /config/ryazhahand/downloads/zip-url/ /
delete /config/ryazhahand/downloads/{json_file(0,assets,{json_file_source(*,download-entry)},name)}
delete /config/ryazhahand/downloads/zip-url.json

try:
delete /config/ryazhahand/downloads/zip-url-version.json
download {json_file_source(*,zip-url-version)} /config/ryazhahand/downloads/zip-url-version.json
json_file /config/ryazhahand/downloads/zip-url-version.json
download {json_file(assets,{json_file_source(*,download-entry)},browser_download_url)} /config/ryazhahand/downloads/{json_file(assets,{json_file_source(*,download-entry)},name)}
unzip /config/ryazhahand/downloads/{json_file(assets,{json_file_source(*,download-entry)},name)} /config/ryazhahand/downloads/zip-url-version/
move /config/ryazhahand/downloads/zip-url-version/ /
delete /config/ryazhahand/downloads/{json_file(assets,{json_file_source(*,download-entry)},name)}
delete /config/ryazhahand/downloads/zip-url-version.json

try:
; for if file is .ovl
delete /config/ryazhahand/downloads/ovl-url.json
download {json_file_source(*,ovl-url)} /config/ryazhahand/downloads/ovl-url.json
json_file /config/ryazhahand/downloads/ovl-url.json
download {json_file(0,assets,{json_file_source(*,download-entry)},browser_download_url)}  /config/ryazhahand/downloads/{json_file(0,assets,{json_file_source(*,download-entry)},name)}
move /config/ryazhahand/downloads/{json_file(0,assets,{json_file_source(*,download-entry)},name)} /switch/.overlays/
delete /config/ryazhahand/downloads/ovl-url.json

[*Install Package]
try:
json_file_source '/switch/.packages/Easy Installer/packages.json' name
download {json_file_source(*,file-1-url)} /switch/.packages/{json_file_source(*,label)}/
download {json_file_source(*,file-2-url)} /switch/.packages/{json_file_source(*,label)}/
download {json_file_source(*,file-3-url)} /switch/.packages/{json_file_source(*,label)}/
download {json_file_source(*,file-4-url)} /switch/.packages/{json_file_source(*,label)}/
download {json_file_source(*,file-5-url)} /switch/.packages/{json_file_source(*,label)}/

[*Install Music]
try:
json_file_source '/switch/.packages/Easy Installer/music.json' name
delete /config/ryazhahand/downloads/music.zip
download {json_file_source(*,url)} /config/ryazhahand/downloads/music.zip
unzip /config/ryazhahand/downloads/music.zip /music/{json_file_source(*,label)}/
;delete /config/ryazhahand/downloads/music.zip

[*Install Others]
[FPSLocker-Warehouse - latest]
try:
download https://github.com/masagrator/FPSLocker-Warehouse/archive/refs/heads/main.zip /config/ryazhahand/downloads/FPSLocker-Warehouse-main.zip
unzip /config/ryazhahand/downloads/FPSLocker-Warehouse-main.zip /config/ryazhahand/downloads/
move /config/ryazhahand/downloads/FPSLocker-Warehouse-main/SaltySD/ /SaltySD/
move /config/ryazhahand/downloads/FPSLocker-Warehouse-main/atmosphere/ /atmosphere/
delete /config/ryazhahand/downloads/FPSLocker-Warehouse-main/
delete /config/ryazhahand/downloads/FPSLocker-Warehouse-main.zip

[Switch-OC-Suite (no kip) - latest]
try:
download https://github.com/hanai3Bi/Switch-OC-Suite/releases/latest/download/AIO.zip /config/ryazhahand/downloads/
unzip /config/ryazhahand/downloads/AIO.zip /config/ryazhahand/downloads/AIO/
move /config/ryazhahand/downloads/AIO/atmosphere/contents/ /atmosphere/contents/
move /config/ryazhahand/downloads/AIO/config/ /config/
move /config/ryazhahand/downloads/AIO/switch/ /switch/
delete /config/ryazhahand/downloads/AIO/
delete /config/ryazhahand/downloads/AIO.zip

[Commands]
[Package Info]
